### ISSUE TITLE
"Stable" format for coverage

### ISSUE THREAD

**Issue by tmysik** [nette/tester#151]
Currently, code coverage generates an HTML page which is good for humans. But for other tools (like NetBeans in my case ;), it would be much better to have e.g. XML file, preferably in Clover format (this format is widely used and contains information that perfectly suits our needs).

Thanks.

**Comment by milo** [comment]
@matej21 How does it work with phpStorm for you? I mean, how do you load the generated XML by phpStorm?

**Comment by matej21** [comment]
@milo Tools/Show code coverage data

**Comment by milo** [comment]
Indeed! Thanks.

**Comment by milo** [comment]
WIP PR #196

**Comment by jkuchar** [comment]
This looks like ready for closing :)
