### ISSUE TITLE
E_WARNING: flock(): Tester\FileMock::stream_lock is not implemented!

### ISSUE THREAD

**Issue by hrach** [nette/tester#178]
I don't care about actual locking ... :-)

**Comment by milo** [comment]
Are there any cases, that someone actually wants the FileMock locking to work properly? I'm asking before I'll send PR with hardcoded `return TRUE`.

**Comment by hrach** [comment]
@milo well, that's the question. What if you would like to test you implementation of locking? I think thath we should probably do this correctly...

**Comment by milo** [comment]
Hard to say how, when FileMock internal filenames are non-deterministic across the PHP processes.

**Comment by dg** [comment]
FileMock is not locking, so return FALSE seems logical.

**Comment by dg** [comment]
ping @hrach

**Comment by hrach** [comment]
Dunno what are you asking. If locking won't be implemented properly, FileMock can behave wrongly. If ping mens "please, would you prepare pull request", then I have to apologize I have no time it the near future, maybe later (in two months?). But of course, we can close it because of human timeout.

**Comment by milo** [comment]
Human timeout

**Comment by milo** [comment]
Supriiiiise :smile:

**Comment by fprochazka** [comment]
:smile:

**Comment by dg** [comment]
It is interesting to realize that @hrach needs to write [this](https://github.com/nette/tester/commit/f733153ba8e8305e7912284e51b7f8801a0f40c1) half a year.

**Comment by hrach** [comment]
Because I have to solve hidden bc breaks. Priority matters.
