### ISSUE TITLE
Skip one particular test

### ISSUE THREAD

**Issue by tsusanka** [nette/tester#179]
I know there is a way to skip a whole file of tests using anotation like this:

``` php
/**
 * @skip
 */
class Test extends TestCase
```

However, is there a way to skip one particular test in a file with more tests? Like so:

``` php
class Test extends TestCase
{
  public function testA()
  {
    // assert something
  }

  /**
   * @skip
   */
  public function testB()
  {
     // this is ran (regardless the anotation)
  }
}
```

**Comment by jkuchar** [comment]
I think current state when there is skip annotation for file and not for methods is unintuitive. There should be both or none. And I think it makes more sense to have both? Any argument against?

Ad underscode: It sounds like a magic for me...

**Comment by Fuco1** [comment]
While the underscore at front (I use `x`) is possible it does not report the skipped tests.  Ideally you should be told there are unrun tests so that you either rework them or implement the necessary features.
