### ISSUE TITLE
Feature request: line numbers in textual trace in interchangable format

### ISSUE THREAD

**Issue by fprochazka** [nette/tester#183]
If you have a trace like this

```
  in PhpAmqpLib/Connection/AbstractConnection.php(574) 
   in PhpAmqpLib/Connection/AbstractConnection.php(574) array_push()
   in PhpAmqpLib/Channel/AbstractChannel.php(190) PhpAmqpLib\Connection\AbstractConnection->wait_channel()
   in PhpAmqpLib/Channel/AbstractChannel.php(324) PhpAmqpLib\Channel\AbstractChannel->next_frame()
   in PhpAmqpLib/Connection/AbstractConnection.php(634) PhpAmqpLib\Channel\AbstractChannel->wait()
   in PhpAmqpLib/Connection/AbstractConnection.php(271) PhpAmqpLib\Connection\AbstractConnection->close()
   in PhpAmqpLib/Connection/AbstractConnection.php(260) PhpAmqpLib\Connection\AbstractConnection->safeClose()
   in [internal function]PhpAmqpLib\Connection\AbstractConnection->__destruct()
```

You simply cannot copy the `Connection/AbstractConnection.php(574)`, hit `CTRL + N` to open file, paste and then hit enter - it's a syntax error for the IDE. 

But if you paste `Connection/AbstractConnection.php:574` then you can paste it and you can jump directly to the line.

I propose changing the output format to respect this. I'm wondering, what was the reason to invent our own format?

If this get's accepted, I'll send a pullrequest.

**Comment by Fuco1** [comment]
FWIF, Emacs also understands the `file:line:message` syntax for automatic error handling/navigation.  Virtually all GNU tools use this format, that gives it at least some "authority" (of course, GNU is in no way associated with PHP, so this point isn't very strong)

**Comment by dg** [comment]
I know that it is OT, but the format with parentheses makes output IMHO a bit more readable.

```
  in PhpAmqpLib/Connection/AbstractConnection.php(574) 
   in PhpAmqpLib/Connection/AbstractConnection.php(574) array_push()
   in PhpAmqpLib/Channel/AbstractChannel.php(190) PhpAmqpLib\Connection\AbstractConnection->wait_channel()
   in PhpAmqpLib/Channel/AbstractChannel.php(324) PhpAmqpLib\Channel\AbstractChannel->next_frame()
   in PhpAmqpLib/Connection/AbstractConnection.php(634) PhpAmqpLib\Channel\AbstractChannel->wait()
   in PhpAmqpLib/Connection/AbstractConnection.php(271) PhpAmqpLib\Connection\AbstractConnection->close()
   in PhpAmqpLib/Connection/AbstractConnection.php(260) PhpAmqpLib\Connection\AbstractConnection->safeClose()
   in [internal function]PhpAmqpLib\Connection\AbstractConnection->__destruct()
```

```
  in PhpAmqpLib/Connection/AbstractConnection.php:574 
   in PhpAmqpLib/Connection/AbstractConnection.php:574 array_push()
   in PhpAmqpLib/Channel/AbstractChannel.php:190 PhpAmqpLib\Connection\AbstractConnection->wait_channel()
   in PhpAmqpLib/Channel/AbstractChannel.php:324 PhpAmqpLib\Channel\AbstractChannel->next_frame()
   in PhpAmqpLib/Connection/AbstractConnection.php:634 PhpAmqpLib\Channel\AbstractChannel->wait()
   in PhpAmqpLib/Connection/AbstractConnection.php:271 PhpAmqpLib\Connection\AbstractConnection->close()
   in PhpAmqpLib/Connection/AbstractConnection.php:260 PhpAmqpLib\Connection\AbstractConnection->safeClose()
   in [internal function]PhpAmqpLib\Connection\AbstractConnection->__destruct()
```
```

**Comment by fprochazka** [comment]
What about a static-property switch?

**Comment by EdaCZ** [comment]
It would be nice to have this. Tester would be a bit better tool than now from my point of view. 
Why is it problem to add at least static property for switch formats?

**Comment by fprochazka** [comment]
I don't think it's a problem. Whole tester is static anyway.

**Comment by dg** [comment]
:-1:

**Comment by fprochazka** [comment]
It's gonna take phpstorm ages to implement it. While this can be done today and it will really be an improvement in usability for me. Only question is how :)

**Comment by dg** [comment]
I don't care if Tester uses parentheses or colon, but static switch is really bad idea.

**Comment by dg** [comment]
(@fprochazka is "bad" acceptable word or am I agressive? :-)) )

**Comment by fprochazka** [comment]
@dg so [half](https://github.com/nette/tester/blob/f865b0036805f59a90ba94a26a19d96fc4914a09/Tester/Framework/Environment.php#L25-L32) [of the](https://github.com/nette/tester/blob/f865b0036805f59a90ba94a26a19d96fc4914a09/Tester/Framework/Assert.php#L40) [tester](https://github.com/nette/tester/blob/f865b0036805f59a90ba94a26a19d96fc4914a09/Tester/Framework/Dumper.php#L16-L19) is basically a "really bad idea"? Ofcourse there are other and better ways, but when I look into the current codebase, static property doesn't seem like **such** a bad idea.

As it needs to propagate to the actual tests, I think it would be okey to use an environment variable. Which can be set in IDE, in bash startup script or in bootstrap of tests, if needed. What do you think about that? What way of setting up the different formatting would be acceptable for you?

--------

I don't think so, we've had a lovely discussion so far :) I suppose your [comment](https://github.com/nette/tester/issues/183#issuecomment-70377765) is reaction [to this](https://twitter.com/EdaCZ/status/556506410213994496)?

Let's just get back to this topic and solve this as fast as possible, so we don't loose time on such a minor (but really annoying!!) problem.

**Comment by dg** [comment]
It is not about „static property“, it is about code garbage, about code that solves extreme rare usecase that should be solved by IDE. You can fix it using output handler or we can change parenthesis to color, but I really don't want to complicate Tester code because of that.

**Comment by fprochazka** [comment]
I just verified it works in [PhpStorm 2016.1.1](https://github.com/nette/tester/issues/313#issuecomment-218990255)
