### ISSUE TITLE
Run the same test with different PHP configurations

### ISSUE THREAD

**Issue by JanTvrdik** [nette/tester#184]
Currently we have `@dataProvider` and `@phpIni`. I would like mix of those two which would allow me to run the same test with different PHP configurations (e.g. with and without magic quotes enabled).

**Comment by milo** [comment]
How to mix it? `@phpIniProvider`? ;) Ideas:

a) clone test when same PHP ini value specified multiple times, e.g:
```
@phpIni magic_quotes_runtime=0
@phpIni magic_quotes_runtime=1
```
but it needs to parse annotation.

b)
Do not implement it and recommend to write two tests with common behaviour PHP file like:
```php
/**
 * @phpIni magic_quotes_runtime=0
 */

require __DIR__ . '/Test.behaviour.php';
```

```php
/**
 * @phpIni magic_quotes_runtime=1
 */

require __DIR__ . '/Test.behaviour.php';
```
