### ISSUE TITLE
Setting up the right environment

### ISSUE THREAD

**Issue by hrach** [nette/tester#191]
Currently, it's not easy to setup ideal "environemnt"
- to allow run tests via tester
- to alow run tests via php (cli)
- to allow run tests via browser

Mostly, I am talking about debugger & dumping. This is my configuration, wich wasn't so easy to make :-)

bootstrap.php

``` php
Environment::setup();

$configurator = new Configurator();

if (!(getenv(Environment::RUNNER) === '1') {
    $configurator->enableDebugger(__DIR__ . '/log'); // show tracy bluescreen in browser
} else {
    ini_set('html_errors', 'Off'); // print xdebug output without html
    header('Content-type: text/plain'); // dumps like in console
    putenv('ANSICON=TRUE'); // dumps like in console
}
// ...
return $configurator->createContainer();

```

**Comment by milo** [comment]
I'm not sure what you want :) Update doc? Anyway...
```php
if (getenv(Environment::RUNNER)) {
    # Runner
} elseif (PHP_SAPI === 'cli') {
    # CLI
} else {
    # Browser
}
```
The Environment::setup() [does](https://github.com/nette/tester/blob/76153d57bd1175142e4fa800e8782a7449d11136/Tester/Framework/Environment.php#L82) some basic CLI setting.

**Comment by dg** [comment]
ping @hrach

**Comment by hrach** [comment]
My proposal is: implement this to Environment::setup(). I do this in every project.

```
if (getenv(Environment::RUNNER)) {
    # Runner
    header('Content-type: text/plain');
    putenv('ANSICON=TRUE');
}
```

It correctly setups the environment, as it would be run by console.

**Comment by milo** [comment]
@hrach 
Set the `ANSICON` env in your environment. Runner [keeps](https://github.com/nette/tester/blob/2ce1cd9a6d7012ba059efa08613d5cd6e50c6560/Tester/Runner/Job.php#L84) the environment for tests.

Not sure about `Content-type`. It matters only when run by `php-cgi` (or not?). And I would expect default PHP's `Content-Type`.
