### ISSUE TITLE
Make php default runner (swap with php-cgi)

### ISSUE THREAD

**Issue by hrach** [nette/tester#197]
Recent changes in nette components (also) proved that  php-cgi as default runner is not so important & useful. The most of tests are unit and integration tests, which actually don't depend on http/cgi environment. 

The meaning and importance of using php-cgi could be just mentioned in doc.

This will actually also make support for running under hhvm by default.

**Comment by dg** [comment]
#168

**Comment by Majkl578** [comment]
I'm still :+1: for this. Btw. has anyone done any benchmarks with php-cli vs. php-cgi?

**Comment by dg** [comment]
I would be :+1: but it is serious BC break.

**Comment by xificurk** [comment]
I'm curious - how serious?
(Disclaimer: no php-cgi executable on any of my systems/servers)

**Comment by milo** [comment]
The facts
- PHP CLI is a standalone package on Linux, may not be installed.
- PHP CLI [bug](https://github.com/nette/tester/blob/675963971d326b5e348b2bab865adf34a7759ce9/tests/Runner.edge.phpt#L34-L39)
  - most dangerous for PHP-CLI 5.4.0 to 5.4.6 (it can mute test fail)
  - false positive test failing for PHP-CLI 5.3.0+

- HTTP code [checking](https://github.com/nette/tester/blob/675963971d326b5e348b2bab865adf34a7759ce9/Tester/Runner/TestHandler.php#L180)
  - code cannot be checked under the CLI, it may mute serious test fails
  - maybe mark test as skipped is a solution

Any other BC break things?

**Comment by hrach** [comment]
Ad php cli - it's much more common to have php-cli installed than php-cgi.
Ad php cli bugs - does it affects only result code tests or Tester relies on this?
Ad http code checking - well, the muting is the tester bug.

I'm ok doing this BC break in 2.0.

**Comment by xificurk** [comment]
> PHP CLI is a standalone package on Linux, may not be installed.

This is of course unsubstantiated generalizations... e.g. on Gentoo **Linux** both binaries are installed by one package, but building of both cgi and/or cli binary may be switched on/off by USE flags. The default setting for linux profile is build cli only.

**Comment by Vrtak-CZ** [comment]
I think most people have CLI on server because **composer** (I don't know anyone who run composer with `php-cgi`).

**Comment by milo** [comment]
When CLI become default, what about tests with `@httpCode`? Should pass (as now) or skip?

If pass, it can hide failing asserts. User expects that HTTP code is tested.
If skip, it may hide even more failing asserts. User may not note, that some tests are skipped now.

**Comment by hrach** [comment]
> If skip, it may hide even more failing asserts. User may not note, that some tests are skipped now.

Let's skip them. User's should pay attention when upgrading.

**Comment by JanTvrdik** [comment]
The current behavior is correct. I want to be able to run the test under multiple interpreters. Skipping the test forces me to use php-cgi

**Comment by dg** [comment]
I would not change anything, but we can add notice when tester is called without `-p`. Similary to notice when is called withnout `-c`. And remove it in half a year, cca.
