### ISSUE TITLE
Fix documentation for Assert::fail

### ISSUE THREAD

**Issue by Fuco1** [nette/tester#198]
The english (as well as czech) documentation for `Assert::fail` (http://tester.nette.org/en/#toc-assert-fail) lists the arguments as

    Assert::fail($message, $expected = NULL, $actual = NULL)

In reality, they are swapped, see: https://github.com/nette/tester/blob/master/Tester/Framework/Assert.php#L423

Now, I guess it is not possible to fix the code because that would break BC, but considering *all* other asserts have the order `$expected, $actual` this is very unexpected (and indeed brought me quite some headache until I figured I'd check the sources).  Is there some reasoning behind this choice?

**Comment by milo** [comment]
Doc fixed. 

Not sure about the reason, but I often use `fail()` with an `$actual` only.

**Comment by dg** [comment]
Yes, the reason it that $actual is always present, but $expected is not:

- `self::fail('%1 should be truthy', $actual)`
- `self::fail('%1 should be string or array', $actual);`

**Comment by Fuco1** [comment]
Thanks. I believe we can close then?
