### ISSUE TITLE
Feature request: same interface as TestCase in PHP Unit

### ISSUE THREAD

**Issue by EdaCZ** [nette/tester#199]
I have projects, where I use PHPUnit. The PHPUnit TestCase class has methods for asserting, so you can call asserts like this:
```php
class MyTest extends PHPUnit_Extensions_Database_TestCase 
{
	public function testMyValues()
	{
		$this->assertEquals('expected', 'expected');
		$this->assertTrue(true);
		...
	}
}
```
It would be practical to use same interface in Tester, but it doesnt have these methods in its TestCase class (as shortcuts for static asserts).

What is your opinion? Shlould I send PR?

It could be nice argument for PHPUnit users to switch to Nette Tester. 
"You dont need to rewrite your tests, simply switch to lightweight Nette Tester, we have same interface."

**Comment by fprochazka** [comment]
I don't think it should be in this library. But creating phpunit-to-tester bridge would be really nice!

**Comment by dg** [comment]
It is not intention of Tester to be 100% compatible with PHPUnit.

**Comment by JanTvrdik** [comment]
I actually started working on this a very long time ago. No idea if I still have the code whether it's of any value.

**Comment by fprochazka** [comment]
@EdaCZ is it a problem to implement it as standalone package? I think it would be much better, as the scope of this repository is to provide testing framework, not compatibility with phpunit.

**Comment by milo** [comment]
@EdaCZ That's thing I don't like about phpUnit. The TestCase has 94 `assert*` methods. Imho, misused inheritance.

Maybe it is a nice oportunity to write a Tester's plugin, maybe write it as a trait.
