### ISSUE TITLE
Blank green line in 1.3.1

### ISSUE THREAD

**Issue by o5** [nette/tester#203]
I don't know why, but after update to version 1.3.1, I see blank green line where cursor is located.

![screen shot 2015-02-01 at 01 54 53](https://cloud.githubusercontent.com/assets/218562/5990530/9fa1c7f2-a9b5-11e4-8857-edf70f29d8cd.png)

![screen shot 2015-02-01 at 01 55 13](https://cloud.githubusercontent.com/assets/218562/5990532/a5923534-a9b5-11e4-9937-1e702c6679d4.png)

`iTerm2 Build 2.0.0.20141103`

**Comment by Majkl578** [comment]
Might be bug caused by f865b0036805f59a90ba94a26a19d96fc4914a09.
