### ISSUE TITLE
FR: Make TEST_FILE_EXTENSION customizable

### ISSUE THREAD

**Issue by Fuco1** [nette/tester#205]
We have more than one type of tests (unit, integration, regression and other weirder cases) and it would be useful to be able to run only some of them based on the extension.

Our code is structured in a huge directory tree (thousands of files, up to 5 levels deep) and we prefer to put tests next to the code they test instead of having a copy of the entire structure somewhere aside for each type of test---that would lead to needless multiplication.

A simple `--extension` switch for the cmd interface is enough.  Most testing frameworks support this and I don't see any downside to adding it to `tester` as well.

**Comment by dg** [comment]
`tester *.myext` ?

**Comment by JanTvrdik** [comment]
`find -name '*.ext' | xargs tester`

**Comment by Fuco1** [comment]
That is basically what I'm doing right now.  If we ignore windows platform, I'm OK with sticking to `find` & `xargs` :)

**Comment by JanTvrdik** [comment]
You can easily use `find` + `xargs` even on Windows. Just install Git, [Cmder](http://bliker.github.io/cmder/) or mingw.

**Comment by dg** [comment]
Hmm, `tester *.myext` is not recursive, but maybe it can be

```php
	private function findTests($path)
	{
		if (strpbrk($path, '*?') === FALSE && !file_exists($path)) {
			throw new \InvalidArgumentException("File or directory '$path' not found.");
		}
		if (is_dir($path)) {
			$path .= '/*.' . self::TEST_FILE_EXTENSION;
		}
		foreach (glob(str_replace('[', '[[]', dirname($path)) . '/*', GLOB_ONLYDIR) ?: array() as $dir) {
			$this->findTests($dir . '/' . basename($path));
		}
		foreach (glob(str_replace('[', '[[]', $path)) ?: array() as $file) {
			if (is_file($file)) {
				$this->testHandler->initiate(realpath($file));
			}
		}
	}
```

**Comment by milo** [comment]
Difficult decision. The always-recursive closes choice for `*.phpt` only in one dir. I think, that's the reason why git uses `**` in `.gitignore`. What about:
```
tester tests/**/*.phptu
```

**Comment by JanTvrdik** [comment]
You would need to write `tester '*.ext'` or `tester 'tests/**/*.phptu'` otherwise shell will expand it.

**Comment by milo** [comment]
@JanTvrdik yes, that's typo, edited

**Comment by Fuco1** [comment]
Hmm, the `**` recursive expansion also works in `zsh`, `fish` and probably other shells as well, so for me the problem reduces to just `tester **.phps` (`phps` is the extension we use for system tests).

Still, a shell-independent solution is probably the prefered one.  But I understand that this is a fringe issue and time is better spent elsewhere.

**Comment by TomasVotruba** [comment]
@Fuco1 Thanks for closing the issue even after such a long time.

I'm curious, wow did you resolved that in the end?

**Comment by Fuco1** [comment]
We ended up writing our own runner for tests which aren't unit tests, there were other problems `nette/tester` wasn't built for (like parallelism constraints between tests and so on).  So now we only use `nette/tester` to run phpt files and we are 100% satisfied :)

**Comment by TomasVotruba** [comment]
@Fuco1 That sounds great :) I'm glad you found a way that suits you.
Is it available as open-source somewhere?

**Comment by Fuco1** [comment]
Unfortunately not yet, there is some code we can't open, and it's not really written in a way that would be reusable for others.

We might add the features to tester if we figure out some good way to do it though.

**Comment by TomasVotruba** [comment]
I see. Thanks for your responses.
