### ISSUE TITLE
Problem with combine Enviroment::lock() and @dataProvider

### ISSUE THREAD

**Issue by Budry** [nette/tester#208]
Hi,
I have problem with Enviroment::lock() and `@dataProvider` annotation.

My example code:
```php
protected function setUp()
{
	Environment::lock("database", dirname(TEMP_DIR));
        // ...
}

/**
 * @dataProvider provideMaxDepth
 */
public function testMaxDepth($depth, $expected)
{
	// ...
}

public function provideMaxDepth()
{
	return [
		[4, [1, 2, 3, 4]],
		[5, [1, 2, 3, 4, 5, 6]]
	];
}
```

The problem is that `testMaxDepth` test is run only one and then test is frozen. If I remove lock() and run only on 1 thread all is OK, but is not good way....

**Comment by milo** [comment]
Use the `Environment::lock()` outside of class. Before a TestCase run.

**Comment by Budry** [comment]
Oh, thanks! :)
