### ISSUE TITLE
@skipOthers

### ISSUE THREAD

**Issue by hrach** [nette/tester#218]
This is similar to https://github.com/nette/tester/issues/179. Personally, I quite often need to disable other tests methods in testcase to test only one method. Adding @skip to other methods is demanding. So I would appriciate something like @skipOthers annotation, which would allow test only the specific testcase method. There are two reason why it's convenient:
- if test is run by browser / php, there is no test method sandboxing.
- if test has more methods and some sections, it would be faster to test it.

**Comment by fprochazka** [comment]
Are you aware you can run just one testing method by running the file ?

```bash
$ php tests/MyTest.phpt testMethod
```

**Comment by hrach** [comment]
This was the mistake which was presented on posobota, without having clue why it's working. This is undocumented internal fetarue, which don't work with bin/tester - that was the ackward part of talk when someone (don't know who) didn't know why it's not working. So I am aware, but it is not solution, for example it will not run test based on dataprovider, etc.

**Comment by fprochazka** [comment]
I believe it will run tests even with data provider :)

**Comment by hrach** [comment]
I was talking about file dataprovider: https://github.com/nette/tester/blob/a3139819bb013256c7fc64fea37070102dab2c30/Tester/Framework/Environment.php#L168 I would have to run `php test.phpt testMethod` with `--dataprovider` manually.

**Comment by milo** [comment]
One possibility is `$testCase->run('testMethod');` calling.

**Comment by hrach** [comment]
Good point! For now It's enough for me :)

**Comment by hrach** [comment]
@milo It's not working!

```
Cannot list TestCase methods in file '...\relationships.oneHasMany.phpt'. Do you call TestCase::run() in it?
```

**Comment by hrach** [comment]
The current solution does not solve|fix this issue. If I pass the method name as an argument, it runs the testcase only one and ignores @dataProvider.

**Comment by milo** [comment]
Will be solved by https://github.com/nette/tester/commit/710c4b5957f95147a67b6d43f672cea9de545d61 where is a data provider applied.

**Comment by dg** [comment]
So can we release new version?

**Comment by hrach** [comment]
Just side note: in phpunit there is a cli --filter option, which allows you to filter method like 
`phpunit --filter '::testFoo' mytest.phpt`. It's pretty addictive. The advantage is that you don't need to update your test, you can reuse history in console, ...

**Comment by milo** [comment]
@hrach `php path/to/test-case.phpt --method=testMe` will work as well

**Comment by milo** [comment]
@dg #261

**Comment by hrach** [comment]
@milo yes, but we are at the beginning, it's not run multipletimes with dataprovider options, pretty exception output, etc.

**Comment by milo** [comment]
Oh, forgot about `@dataProvider` for file. But I don't undestand to

> exception output, etc.

Ouput is the same, colorized and nice. What means `etc.`?

**Comment by hrach** [comment]
Sorry, you are probably right that other things are ok. I had the feeling ... but I may have been wrong.

**Comment by hrach** [comment]
After this https://github.com/nette/tester/commit/f3b81790acf2355d5a06fc6e553ca8d76c065fe9 it's quite more compilated do to it... so I'd love the annotation :-)

**Comment by hrach** [comment]
Do you have any opinion on this? I see two possible ways:
- introduce skipOthers
- add CLI argument

**Comment by milo** [comment]
Since Tester is focused more to "plain" tests, not TestCased tests, I think that `@skipOthers` is better choice.
But its usage must be conditioned by `@testCase` usage. Is that OK for you?

**Comment by hrach** [comment]
Yeah, I'm ok with that requirement.
