### ISSUE TITLE
XDebug's path/branch coverage

### ISSUE THREAD

**Issue by JanTvrdik** [nette/tester#223]
XDebug in version 2.3 added a new type of code coverage called "path/branch coverage" (http://derickrethans.nl/path-branch-coverage.html).

(I didn't research how useful it would actually be, just wanted to start a discussion).

**Comment by milo** [comment]
As I quickly tested it, it is pretty useful, but extremly slow :)

**Comment by jkuchar** [comment]
Cool! Path coverage can be much more expressive then line-coverage.
