### ISSUE TITLE
Coverage: folder skip option

### ISSUE THREAD

**Issue by f3l1x** [nette/tester#225]
At this moment there are only 2 options.

```
--coverage FILE
```

```
--coverage-src FOLDER
```

I would like to skip some nested folder. Something like

```
--coverage-skip FOLDER/A
```

Is there any other way how to do that?

**Comment by milo** [comment]
It's not possible now. Just curious... what is the `FOLDER/A` contents to be skipped?

**Comment by f3l1x** [comment]
Sure, It's 3rd part library which is under our project namespace and there's no composer package.

**Comment by f3l1x** [comment]
I think I can accomplish this issue with this commit https://github.com/nette/tester/commit/2286131c7bd9d47ea7fc638480d4ea1f2ace37aa. Thanks.
