### ISSUE TITLE
Possibility to keep classic and specific output at the same time

### ISSUE THREAD

**Issue by mrtnzlml** [nette/tester#228]
According to [this tweet](https://twitter.com/MiloNemilo/status/593779817088159744) it's not possible to run tests with classic output and junit output at the same time (or generate more outputs). It would be nice to have both of them (or more outputs at once). Maybe something like this:

```
> tester -o junit --output-dir testsOutputDir
```
Or:
```
> tester --junit junitOutputDir
```

Or something like that (`--preserve-log` ?). What do you think?

**Comment by milo** [comment]
Actually it's possible in a `--setup script.php`
```php
$runner->outputHandlers[] = new Tester\Runner\Output\JUnitPrinter($runner, 'file.xml');
```
but it's not possible by command line.

My draft allows an `-o` multiple times with optional parameter like:
```
tester -o junit:dir/file.xml
```

**Comment by mrtnzlml** [comment]
Obviously no one is interested in this feature and in fact me neither. There is possibility to do it using `--setup` argument. Thanks... :)
