### ISSUE TITLE
Random freezes with PHP 7

### ISSUE THREAD

**Issue by JanTvrdik** [nette/tester#233]
When running tests on PHP 7 (alpha 1 x64 NTS both php and php-cgi executable), it sometimes stops for unknown reason in the middle of the process. No errors, no messages. It just does not finish. I spend a little bit of time analyzing the issue and seems to freeze on [stream_get_contents](https://github.com/nette/tester/blob/a29a3e8fd3084b411c1bc9057460bce8fccd9b4a/src/Runner/Job.php#L112) call.

Anyone having similar issue (e. g. when you run tests of tester itself)? 

---

Video demonstration http://screencast.com/t/yySpyPZ7L (the php executable crash was caused by https://github.com/php/php-src/commit/dc37d3e8c2248f4f4437547bc7225276e22ea41d).

---

Another note: it works fine with older snapshot I have (2015-06-08), so they must have broken this very recently.

**Comment by Majkl578** [comment]
Haven't seen this behavior on Linux yet.
```
PHP 7.0.0-dev (cli) (built: Jun 15 2015 01:20:21) (DEBUG)
```
php/php-src@6cb7b4884 + trowski/php-src@throwable-interface

**Comment by JanTvrdik** [comment]
Possible related https://github.com/php/php-src/commit/79ca2b06b6f364b3b10cdd7b5cf36f0d5abc0caf

**Comment by dg** [comment]
@JanTvrdik  Is it still relevant?

**Comment by JanTvrdik** [comment]
It's seems to be working fine now.
