### ISSUE TITLE
Remove TestCase::run() $method parameter

### ISSUE THREAD

**Issue by milo** [nette/tester#244]
Since 710c4b5957f95147a67b6d43f672cea9de545d61, single TestCase test can be invoked by `TestCase::runTest($method)`. The [`$method`](https://github.com/nette/tester/blob/1a4b434b93fe6786a7499b674533d29f303718a5/src/Framework/TestCase.php#L25) parameter from `TestCase::run()` can be removed to preserve only a single way.

**Comment by MartinMystikJonas** [comment]
Would not be better to use run every time for consistency a make runTest protected?
