### ISSUE TITLE
RFC: TestCase events (simplify modularity)

### ISSUE THREAD

**Issue by MartinMystikJonas** [nette/tester#245]
Sometimes we use in our tests some additional tools (Mockista, mockery, database connection, PHP server, memcached, dummy presenter, different container configurations,  ...). Current solution is to create some base TestCases with different combinations of these tools. But it get complicated as more and more tools used. Not mentioning you need to call all of them in tearDown and setUp correctly.

We think about solution inspired by Codeception modules. What we need to create something like that is ability of modules to hook on some TestCAse lifecycle events.

Co we suggest to add to TestCase these events which can be hooked from modules to extends TestCAse behaviour:
- beforeSetUp
- afterSetUp
- beforeTearDown
- afterTearDown
- beforeRunTest
- afterRunTest

Usage for Mockery in some module then can look like:

```
class MockeryModule {

  public static function register(TestCase $testCase) {
    $testCase->afterTearDown[] = function($testCase) {
      Mockery::close();
    }
  }

}
```

Or for database extension:

```
class DatabaseModule {

  public static function register(TestCase $testCase) {
    $testCase->beforeSetUp[] = function($testCase) {
      $this->database->connect();
      $this->database->importData();
    }
    $testCase->afterTearDown[] = function($testCase) {
      $this->database->clearData();
    }
  }

}
```

Concept of modules need to be think throught and is not ready yet. It probably should be addon. But adding this events is first step to be able to do this, it is not BC break and can improve extendability of TestCase.

Proposed solution in PR #246

**Comment by milo** [comment]
I [opened](http://forum.nette.org/en/24028-rfc-testcase-events-for-tester#p161184) discussion.
