### ISSUE TITLE
tearDown not executed when test fails with error or exception

### ISSUE THREAD

**Issue by richard-ejem** [nette/tester#254]
I suppose this is a bug - this tidy method should be executed no matter if the test succeeds or fails. Actually tearDown works if the test fails on assertion, but not on error/exception.

//Edit: it works on exception, but not on any runtime error.

Please confirm it is a bug, I can fix and pullrequest it.

**Comment by milo** [comment]
I guess it's already fixed https://github.com/nette/tester/commit/fc6d85565097528168ebd9f106744a22d8155ad1

**Comment by MartinMystikJonas** [comment]
TearDown is not executed when PHP stops on Fatal error I think. For all other errors and exceptions it works.

@milo: Maybe add tearDown to shutdown_handler?

**Comment by richard-ejem** [comment]
Confirming it does not work on errors, even E_NOTICE.
try this:

	class ErroredTest extends Tester\TestCase
	{
		public static $tornDown = FALSE;
		protected function tearDown() { self::$tornDown = TRUE; }
		public function testPublic() { ++$a; }
	}
	
	register_shutdown_function(function() {
		Assert::true(ErroredTest::$tornDown);
		exit(0); //to reset the exit code back from 255 after E_NOTICE killed the script
	});
	
	$test = new ErroredTest;
	$test->run();

Registering teardown to shutdown function seems legit.

**Comment by milo** [comment]
Test will fail on unexpected error. There is no need to run `tearDown()`.

**Comment by richard-ejem** [comment]
It will skip tearDown on unexpected error, but not on unexpected exception, isn't that just inconsistent?

tearDown is supposed to "tidy after the test", i.e. restore test database state, delete temporary files etc. I am sure this should be done regardless ot the test result, including termination on error.

**Comment by MartinMystikJonas** [comment]
I agree witch @richard-ejem. Not executing tearDown can lead to unexpected bahaviour of following tests.

**Comment by milo** [comment]
Tests must be independent. The only reason for executing `tearDown()` when test method fails, used to be `@throw` annotation. After https://github.com/nette/tester/commit/710c4b5957f95147a67b6d43f672cea9de545d61 it can be removed.

**Comment by richard-ejem** [comment]
@milo what should the tearDown() method  be used for by your opinion?

As i wrote: I think it should tidy database, temp files etc., which should happen regardless of test result.

So, If you say that it is not needed when test ends with error, I assume that you use tearDown for something different, that makes sense when the test succeeds, but not when it fails?

**Comment by milo** [comment]
I'm using it for unlocking and additional assertions. All preparations should be done in `setUp()`, it prepares environment for testing.

On test fail, I need to preserve environment as is as much as possible.

**Comment by richard-ejem** [comment]
OK, that's quite valid reason. Thanks, it's clear to me now that tearDown() makes sense only for succeeding tests to cleanup before following test methods.
And I just figured out that in case I really need to cleanup some mess regardless of test result (mentioned temp files etc.), I can use TestCase::__destruct, which executes even when failing with notice :)

Therefore I think the correct solution is to not execute teardown even when the test fails on exception, am I correct? If yes, I'll change the pull request to do that.

**Comment by milo** [comment]
I already opened #257, let's wait for David's opinion on this.

**Comment by richard-ejem** [comment]
OK, we may close it there, thanks ;)
(and I'm happy that I've found a valid usage of a destructor :D )

**Comment by milo** [comment]
:)

**Comment by MartinMystikJonas** [comment]
@milo I disagree with that solution.

Main reason is that all other test frameworks (PHPUnit, JUnit) execute tearDown after failing test so I think not executing tearDown after failing test can be WTF for many users.

One reason to use tearDown  - sometimes only test itself knows how to properly clean up after himself. Other tests might not know how to clean up properly or only can use some perfomance killing techniques like wipe out and reinitialize entire environment.

Example of what can be done in tearDown is unlocking resources as you said. But if test lock resource and then fails file remain locked and other tests will hang up or fail after timeout.

I agree that sometimes you need to preserve enviromnemt after test fails but I think avoid execution of tearDown is not the right way.

**Comment by hrach** [comment]
> One reason to use tearDown - sometimes only test itself knows how to properly clean up after himself. Other tests might not know how to clean up properly or only can use some perfomance killing techniques like wipe out and reinitialize entire environment.

:+1:

In PhpUnit If I don't want to cleanup env, I modify teardown (override it to be empty, etc.).

**Comment by milo** [comment]
> In PhpUnit If I don't want to cleanup env, I modify teardown (override it to be empty, etc.). 

You override it conditionally when test failed?

**Comment by milo** [comment]
Relay on clean-up in `tearDown()` is false sense of safety. What would you do on fatal errors?

**Comment by richard-ejem** [comment]
Well, as I found out now, when fatal error occurs, my pull request there still catches it and runs teardown :) it works even on parse error on included code.

Destructor is in general not called on fatal error, so maybe the pull request comes back to discussion as I see other people would also welcome it.

**Comment by hrach** [comment]
> You override it conditionally when test failed?

When I need something what has been cleaned up.

**Comment by MartinMystikJonas** [comment]
@milo As I suggested, what about call tearDown forom shutdown_handler? It should work even for fatal errors.

**Comment by milo** [comment]
>> You override it conditionally when test failed?
> When I need something what has been cleaned up.

@hrach You are talking about editing test source code. I'm talking about run time.

> As I suggested, what about call tearDown forom shutdown_handler? It should work even for fatal errors.

@MartinMystikJonas Where would you register it in the `Tester\TestCase`? `__construct()`, `setUp()`, `runTest()`? What if there will be an exception, non autoloaded class or fatal error in `tearDown()`? Will be cleaning-up done or not?

**Comment by milo** [comment]
@richard-ejem Check out [Travis](https://travis-ci.org/nette/tester/builds/80655364).

**Comment by MartinMystikJonas** [comment]
@milo I think best place is in runTest. When there is error in tearDown itself you are in situation with no solution. BUt I think tahat in any other case we should run tearDown whenever possible.

**Comment by dg** [comment]
I am not using TestCase and I have no experience with that. However, I would expect that `tearDown()` is called everytime, no matter if test was succesful.

I see `setUp()` and `tearDown()` as pair that set-ups and cleans environment, ie. creates and deletes resources, temporary files etc. However, from a practical point of view sometimes I not want to delete temporary files when test fails because I want to analyse them, so method `TestCase::hasFailed()` can be useful.

I think that `setUp()` and `tearDown()` must no call any assert, ie. an error in these methods should be considered as fatal test error. Sometimes it is needed to execute assertions on mocking tool - it should be done in method `TestCase::assertPostConditions()`, not in `tearDown()`.

In PHP 7 we can catch PHP fatal errors and easily call tearDown, in PHP 5 we can simulate it via register_shutdown_function. We can implement it in `Tester\Environment`, via new callback `$onFatalError` or etc.

**Comment by richard-ejem** [comment]
@milo oh I didn't notice :( pre-5.4 can be fixed, I've forgotten that closures didn't support $this in 5.3, but I have currently no idea why notice is not caught by php, but only php-cgi

**Comment by richard-ejem** [comment]
@dg yes I simulated it with register_shutdown_function, but as @milo noticed now in Travis, it works only on "php-cgi" binary. I will do more investigation if it can be made working on php binary.

**Comment by MartinMystikJonas** [comment]
@dg Agreed with most of what you said. Only exception is that tearDown should not do any asserts. It is common that tearDown holds fixture asserts. Things like test did not damaged anything, or mocking asserts. I do not think we need extra mechanism for that.

**Comment by dg** [comment]
@richard-ejem there is a lot of cases when you cannot change exit code in register_shutdown_function https://github.com/nette/tester/tree/master/tests/Runner/edge

**Comment by dg** [comment]
@MartinMystikJonas  I assert that the separation of assertions from tearDown can solve a lot of problems.

**Comment by MartinMystikJonas** [comment]
@dg Well I see advantages in that. 

What about alternative approach using  TestCase events as I proposed inPR #246 and #249 ? What do you think about that? We can move that asserts to this events.

**Comment by dg** [comment]
@MartinMystikJonas As I wrote, I do not use TestCase, so I do not know, I can't imagine what it is useful for. 

For `Mockery::close()` I need only one method which will be called after successul test, so one method with good name is for me better than a lot of events.

**Comment by MartinMystikJonas** [comment]
This events are planned for more usages. I would like to implement something like Codeception modules with Nette tester and for that this events are necessary.

**Comment by richard-ejem** [comment]
@dg so maybe if the exit code cannot be changed in register_shutdown_function in cli, what about registering custom error handler in TestCase? 
I've finally built a version passing [Travis](https://travis-ci.org/nette/tester/builds/81091447) in all cases - teardown is ran even on errors.
