### ISSUE TITLE
Wrong error message - instead of "normal" "This test forgets to execute an assertion."

### ISSUE THREAD

**Issue by Cactucs** [nette/tester#265]
I have simple tests similar to the one in sandbox. I run them via bootstrap.php a got an error: `Error: This test forgets to execute an assertion.` I had only one test case class with one test* method where Assert is.

But when I add breakpoint to the line where the errror message is printed out and dump `$error` I got this:
```
array(4) {
  'type' =>
  int(2)
  'message' =>
  string(72) "stream_wrapper_unregister(): Unable to unregister protocol nette.safe://"
  'file' =>
  string(90) "/project-path/vendor/nette/safe-stream/src/SafeStream/SafeStream.php"
  'line' =>
  int(55)
}
```

I don't think that the error message suits the error well.

**Comment by dg** [comment]
Do you have any assertion in your test? If you have not, Tester prints `Error: This test forgets to execute an assertion`.

**Comment by Cactucs** [comment]
There is but it's not executed, because the initialisation fails ansld Tester catches it and prints this message.

**Comment by dg** [comment]
Why initialisation fails?

**Comment by Cactucs** [comment]
Because, as stated above, `stream_wrapper_unregister(): Unable to unregister protocol nette.safe://`.

**Comment by dg** [comment]
No, it is not reason. There is `@` is souce code. Why it fails?

**Comment by milo** [comment]
I guess, it's related to #266. I probably introduced the bug [here](https://github.com/nette/tester/blob/e4cd7409ee25b6c16bc80717ef58abe4cb589cff/src/Framework/TestCase.php#L109). `error_reporting() === 0` is not checked. Working on fix...

**Comment by milo** [comment]
@Cactucs If you can, could you try #267?

**Comment by milo** [comment]
@Cactucs I cannot reproduce it (on master, without #267 fix). Do you call `$testCase->run()`?

```php
require __DIR__ . '/../src/bootstrap.php';

class Test extends Tester\TestCase
{
	public function testMe()
	{
		@mkdir('/tmp/foo/bar/baz');
		Tester\Assert::true(TRUE);
	}
}

(new Test)->run();  # Here, do you call it?
```

**Comment by Cactucs** [comment]
Now, I switched to master. Everything the same.

There is another thing. This executes everything OK (empty output on stdout): 
```
$ php tests/ArnikaInfoTest.phpt 
```

But this show an error:
```
$ php tests/bootstrap.php 

Error: This test forgets to execute an assertion.
```

The first case executes the test, the second not. (Tested by adding `echo` to test)

bootstrap.php
```
<?php

require __DIR__ . '/../vendor/autoload.php';

if (!class_exists('Tester\Assert')) {
        echo "Install Nette Tester using `composer update --dev`\n";
        exit(1);
}

Tester\Environment::setup();

define('TESTS_DATA_DIR', __DIR__ . '/data');

$configurator = new Nette\Configurator;
$configurator->setDebugMode(FALSE);
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
        ->addDirectory(__DIR__ . '/../app')
        ->register();

$configurator->addConfig(__DIR__ . '/../app/config/config.neon');
$configurator->addConfig(__DIR__ . '/../app/config/config.local.neon');
return $configurator->createContainer();
```

TheTest.php (altered): 
```
namespace Test;

use App\Toolbox\FooClass;
use Nette,
	Tester,
	Tester\Assert;

$container = require __DIR__ . '/bootstrap.php';


class TheTest extends Tester\TestCase
{
	private $container;


	function __construct(Nette\DI\Container $container)
	{
		$this->container = $container;
	}

	function testTableGenerating()
	{
		$data = file_get_contents(TESTS_DATA_DIR . '/foo.txt');
		$return = FooClass::doFoo($data);
		$expected = file_get_contents(TESTS_DATA_DIR . '/foo-result.txt');
		Assert::equal($expected, $return, 'Foo executing');
	}

}


$test = new FooClass($container);
$test->run();
```

**Comment by Cactucs** [comment]
I created new project `composer create-project nette/sandbox foo` and run the sample tests.
This is the output:
 ``` 
$ php tests/bootstrap.php 

Error: This test forgets to execute an assertion.
$ php tests/ExampleTest.phpt
```
*(The second command has empty output.)*

**Comment by dg** [comment]
Where is problem?

**Comment by Cactucs** [comment]
That once it outputs an error and doesn't execute test (running via bootstrap.php) and once it runs the test (running via TheTest.php).

**Comment by dg** [comment]
In bootstrap is no assertion so it prints error.

**Comment by Cactucs** [comment]
Thanks for help. I taught that bootstrap launches all the tests... Now I found out that that's not true. (I don't know where does this idea came from)

Sorry for opening useless issue...
