### ISSUE TITLE
PHPUnit compatibility

### ISSUE THREAD

**Issue by janmarek** [nette/tester#273]
Hi, it would be nice to have a compatibility layer for users who want to try/use Nette Tester but have their tests written for phpunit.

I suggest to write a special `PhpUnitCompatibleTestCase` class with support of:

* PHPUnit-style assert methods
* PHPUnit annotations (expectedException, expectedExceptionCode, exceptedExceptionMessage, dataProvider is already supported)
* ability to be executed without calling (new TestCase())->run();

What do you guys think?

**Comment by JanTvrdik** [comment]
https://github.com/nette/tester/issues/199

**Comment by dg** [comment]
But it can be useful as extension.
