### ISSUE TITLE
Coverage of the closing brace after redirect()

### ISSUE THREAD

**Issue by Janiczek** [nette/tester#274]
The intuition is that in this code the closing braces of the method should be also counted in code coverage, because the `$this->redirect(...)` is the last line of the method:

![redirect](https://cloud.githubusercontent.com/assets/149425/11301145/fc6c0180-8f94-11e5-843d-e6e032422b0a.png)

Can one solve it somehow or do you just ignore it?

**Comment by milo** [comment]
The `redirect()` works as an exception. So the method's closing bracket is never reached. Marking it as non-covered is feature of Xdebug.

By other words. It is very hard to write workaround for it :o)

**Comment by Janiczek** [comment]
Sooo fixing this would require more sensible reimplementation of `redirect()` (as a normal function call or something like that :smile: )

**Comment by fprochazka** [comment]
@Janiczek or we might decide that if line contains only a `}` or `{` it should be ignored from coverage.

**Comment by Majkl578** [comment]
How does phpdbg handle this?

**Comment by dg** [comment]
Last `}` is like `return;` and it is really not covered, so Xdebug works fine.

**Comment by Mikulas** [comment]
Phpdbg has way better mapping between opcodes and lines than xdebug. This example in phpdbg:

<img width="492" alt="screenshot 2015-11-20 19 45 25" src="https://cloud.githubusercontent.com/assets/192200/11308669/d88bd8e6-8fbf-11e5-9a63-a97bda9c088c.png">

**Comment by milo** [comment]
@Janiczek As @Mikulas wrote, [phpdbg](https://github.com/nette/tester/blob/3db6187df83a8c9efc591bffac9184dbe32642d8/src/Runner/ZendPhpDbgInterpreter.php) covers such lines. It will be in 1.7.0 release (soon).
