### ISSUE TITLE
Job: cannot run files from PHAR

### ISSUE THREAD

**Issue by milo** [nette/tester#276]
`tester.phar` does not work.

``` sh
cd tools/create-phar
php -d phar.readonly=Off create-phar.php
php tester.phar ../../tests --info --debug

# E_WARNING: proc_open(): CreateProcess failed, error code - 267
```

It's because the Job runs `phar://D:/Web/dev/nette/tester/tools/create-phar/tester.phar/Runner/info.php` and its CWD is inside PHAR. When changed [here](https://github.com/nette/tester/blob/b04e40327b1ec8017cdcd363f0e016df417a8044/src/Runner/Job.php#L93) into:

``` php
strncasecmp($this->file, 'phar://', 7) === 0 ? sys_get_temp_dir() : dirname($this->file)
```

it will work for test files in ordinary file system, but not for the `info.php` inside tester.phar self.

I'm thinking about extraction into system temp dir in this case.

**Comment by jkuchar** [comment]
What about providing `info.php` onto stdin?

**Comment by milo** [comment]
Tester as a PHAR does not work a long time.

**Comment by dg** [comment]
Lets remove it!
