### ISSUE TITLE
Enforce .phpt file extension?

### ISSUE THREAD

**Issue by tsusanka** [nette/tester#278]
Assume having two tests in one directory.

One `FirstTest.phpt`: 

``` php
// ...
class FirstTest extends Tester\TestCase
{
    public function testOk()
    {
        Assert::true(TRUE);
    }
}
```

and `AnotherTest.php`:

``` php
class AnotherTest extends Tester\TestCase
{
    public function testNotOk()
    {
        Assert::true(FALSE);
    }
}
```

You run them with all the other tests using `tester tests/` and you're super happy, since everything passes.

But wait, that's strange. The `AnotherTest` should fail! So you run `tester tests/AnotherTest.php` and it fails. What?! Now you're super-confused. Finally you realize `AnotherTest.php` is not run in the bulk, because it has accidentally wrong extension - `php` instead of `phpt`.

---

How about enforcing the `phpt` extension when running a single test? If I run `tester tests/AnotherText.php` and I get "no tests to run" I know something is wrong.

I'm not sure this is a good solution though, anybody has a better one?

**Comment by fprochazka** [comment]
@tsusanka this could be added to the `Environment::setup()` method, good idea :+1:

**Comment by Mikulas** [comment]
Plus one for addressing this issue, but overall
:-1: create an acceptance test that checks test files are named properly.

**Comment by Majkl578** [comment]
Or rather maybe stop strictly enforcing `.phpt`?

**Comment by tsusanka** [comment]
> Or rather maybe stop strictly enforcing .phpt?

You mean running all php/phpt files found in the directory? Bear in mind bootstraps, scripts etc.

**Comment by Majkl578** [comment]
E.g. PHPUnit looks for files matching `*Test.php` or `*.phpt` by default. It does not force you to use specific format/extension.

**Comment by tsusanka** [comment]
I like that. Some might have reasons not to use `.phpt`, for example [www.reviewable.io](reviewable.io) does not color highlight `.phpt` files as it does `.php` (which is a bug on their side, but still).

**Comment by dg** [comment]
But this does not solve the problem.

**Comment by tsusanka** [comment]
It does not, but it significantly helps. We can as well do both. Change the behavior as @Majkl578 suggests and enforce it during single tests as well.

**Comment by dg** [comment]
The whole nette is not a single test, whose name ends with the `test`. How this helps me when I use accidentally wrong extension?

**Comment by tsusanka** [comment]
But it has `.phpt` extension. I ment enforcing either `.phpt` extension or `*Test.php` filenames. Just a suggestion.

**Comment by dg** [comment]
There are two things:
1) files which Tester looks for
2) checking file extension (and name) 

ad 1) we can probably add `*Test.php` too (in next major version cause it is BC break), but it will not solve this problem
ad 2) it is problematic, because sometimes it is needed to use different extension, for example Testers's testcase use *.phptx files

**Comment by milo** [comment]
What about run all `*.phpt` and `*.php` too and introduce new `@exclude`, `@noTest` (or similar) annotation?

**Comment by tsusanka** [comment]
I'm afraid running all `*.php` files would cause more pain than gain.

I'm suggesting to implement at least @dg 's number 1). It will lower the "wtf factor" and we may leave the file extension checking for later.

Should I create a new issue for 1) to clear things up a bit?

**Comment by milo** [comment]
This issue is OK. I'm tagging it for next major.

**Comment by fprochazka** [comment]
@milo I often mix mock files and helper classes to tests dir, I wouldn't be happy about having to manully exclude them.

**Comment by dg** [comment]
I hope we are talking about `*Test.php`, not `*.php`.
