### ISSUE TITLE
Unable to test multiple http codes within one TestCase

### ISSUE THREAD

**Issue by janedbal** [nette/tester#284]
Lets say I want to test HTTP codes returned from my API somehow like this:

```php
/** @testCase */
class ApiTestCase extends TestCase {

    public function testHttp200() {
        // some api call resulting in http 200
        Assert::same(200, http_response_code());
    }

    public function testHttp404() {
        // some api call resulting in http 404
        Assert::same(404, http_response_code());
    }
}
```

All asserts will pass, but the second test will fail because tester is always expecting HTTP code to be 200 and it cannot be changed for the second test, because ```@httpCode``` annotation can be used only on whole file.

Is there a way to disable checking of HTTP code? Or maybe it would be handy if ```@httpCode``` annotation could be used on test methods.

----

P.S. Yes I can hack it by removing testCase annotation and place testHttp200 as the last test, but that is not proper solution.

**Comment by dg** [comment]
What about to implement file annotation `@httpCode any`?

**Comment by milo** [comment]
@dg Same idea :+1:

**Comment by janedbal** [comment]
@dg Seems ok :)

**Comment by dg** [comment]
Done. It works :-)

**Comment by milo** [comment]
He he :o)

It is easy pick. If someone wants to implement it, there is [hint](https://github.com/nette/tester/blob/436687df7633a87f15192de1984c76f438ce5fdb/src/Runner/TestHandler.php#L180).

**Comment by janedbal** [comment]
```@httpCode WTF``` works too, nice...

**Comment by milo** [comment]
Ha ha ha! Now I really get it :smile:

**Comment by dg** [comment]
@milo btw what about new tester release 1.6.2?

**Comment by milo** [comment]
@dg I was waiting for #258 (and now I see it's done). If you are OK with it, I would merge it and release 1.7.0.

**Comment by dg** [comment]
I need to get a better look at it. Because at first glance I don't like Collector…

**Comment by milo** [comment]
@dg OK, I'll release 1.6.2 in the evening

**Comment by dg** [comment]
Wait, I'll look at it :-)
