### ISSUE TITLE
DataProvider for TestCase method does not work properly

### ISSUE THREAD

**Issue by castamir** [nette/tester#285]
[global DataProvider](https://github.com/castamir/tester-example/blob/master/tests/TestCases/GlobalProvider.phpt) results in 6 tests (dots)
[method DataProvider](https://github.com/castamir/tester-example/blob/master/tests/TestCases/MethodProvider.phpt) results in 2 tests (dots)

see [travis](https://travis-ci.org/castamir/tester-example/jobs/106215424)

Well, I have expected 4 tests (dots)...

-------
EDIT: another unexpected behaviour - I have deleted symbol `?` after `@dataProvider`, see:
```php
    /**
     * @dataProvider ../databases.ini
     */
    public function testAdapter()
    {
        Assert::true(true);
    }
```
An error pops up:
`Fatal error: Call to undefined method TestCases\MethodProvider::../databases.ini() in rootpath\tester-example\vendor\nette\tester\src\Framework\TestCase.php on line 172`

**Comment by milo** [comment]
@castamir I guess you have three records in `databases.ini`. Result is correct. When `@testCase` annoted, Tester runs every `testMethod()` in own process.

a) `@dataProvider` in top of file: 3 records x 2 test methods = 6 results
b) `@dataProvider` in method: 2 test methods = 2 results, every method run 3x in loop, but in scope of single process

I guess I mistified you on PoSobota :) I thought we were talking about something else, about `@testCase` and `@dataProvider` annotations combination.
