### ISSUE TITLE
Disable disabling of loading defaults php.ini.

### ISSUE THREAD

**Issue by hrach** [nette/tester#290]
The current approach is quite obvious - tests should be indenpendent of your current development settings/environment.

However, in the context of docker, containers etc. it complicates things. You have to specifiy the php dependencies & configuration in Dockerfile. Then you have to either wire you tests to dockers' php.ini and tight it up with the php version in the path (/etc/php7.0/php.ini) , or you have to redefine you php.ini settings once again.

The most elegant solution would be an option do disable the `-n`. What do you think?

**Comment by milo** [comment]
The `-n` has to be default. Otherwise it complicates running tests under different PHP versions on the same machine (on the Windows it is extremly annoing with dosens of error pop-ups).

Time to time, as users open issues, I'm thinking about option to disable it. Because the environment is prepared for testing purpose only (e.g. your Docker).

**Comment by hrach** [comment]
Yeah, as you have tagged, it's "friendliness", something like
`php vendor/bin/tester c $(php -r "echo php_ini_loaded_file();")` will solve it for now.

**Comment by JanJakes** [comment]
Actually -c does not load extension configs fron `conf.d`:

```bash
php -n -c $(php -r "echo php_ini_loaded_file();") --ini

Configuration File (php.ini) Path: /usr/local/etc/php/7.0
Loaded Configuration File:         /usr/local/etc/php/7.0/php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)
```

**Comment by JanJakes** [comment]
I've found a workaround using a nasty hack:

```bash
cat $(php -r 'echo php_ini_loaded_file() . " " . str_replace("\n", " ", str_replace(",", "", php_ini_scanned_files()));') > php-tests.ini

php $dir/../vendor/bin/tester -p php -c php-tests.ini $@
```

It would be definitely nice not to have to do that :)

**Comment by fmasa** [comment]
In time of CI tools, containers and VMs used for development the reason behind disabling default php.ini gets obsolete.

Should be the current scenario replaced with _-n_ flag in tester itself?

Run testsuite **with** default php.ini
```sh
vendor/bin/tester tests
```
Run testsuite **without** php.ini
```sh
vendor/bin/tester tests -n
```

**Comment by milo** [comment]
As I wrote above, the `-n` has to be a default behavior. Otherwise it is unpredictable.

I'm plannig to open PR with support "running without `-n`". In meantime thinking how to name the new option. `--keep-default-ini`?

**Comment by dg** [comment]
What about reuse `-c`, something like `-c default`. Just idea.

**Comment by milo** [comment]
I just [found](http://php.net/manual/en/configuration.file.php#configuration.file.scan) that PHP allows you to load additional `*.ini` files in runtime by env var `PHP_INI_SCAN_DIR`. Anyway, it is not applied with `-n`.

New fact in a game :)

**Comment by fmasa** [comment]
What about empty ``-c`` flag?
```sh
vendor/bin/tester tests # Run without php.ini
vendor/bin/tester tests -c # Run with default *.ini
vendor/bin/tester tests -c my-php.ini # Run with specific *.ini
```

**Comment by milo** [comment]
@fmasa Setting (adding) own php.ini should work even with default system INI. I'm thinking about `-C`.

**Comment by fmasa** [comment]
@milo I see. +1 for ``-C``
