### ISSUE TITLE
Coverage: which line was covered by which tests (Clover)

### ISSUE THREAD

**Issue by jkuchar** [nette/tester#294]
1) I find quite useful to know which line was hit by which tests. (and which test his which lines of source) This this visualization is then supported by sonarqube for example. 

2) Another cool thing would be to know how far away was code hit from test itself. You can then know that this code was hit by 25 tests but all hits was at least 5 calls away from test. This means that there is probably no assertion for this particular code in tests.

Do you find this useful?

//EDIT: How it looks when it works: https://youtu.be/Xrj8EPIc8wk?t=18m24s

**Comment by Mikulas** [comment]
I believe it's better to restrict the tests to only generate coverage for scopes set via `@covers` annotation #222

**Comment by jkuchar** [comment]
@Mikulas Yep, covers annotation is more precise (and can work together with 2). Advantage of point 2 is that it "just works" in every codebase.

However this issue was meant to be mainly because of point 1).

**Comment by dg** [comment]
Too complicated.
