### ISSUE TITLE
Open 2.0

### ISSUE THREAD

**Issue by milo** [nette/tester#296]
Can we open v2? I would:
- [x] merge #292 
- [x] release 1.7.1
- [x] open v2 by #259

When some serious bug appears, we can fork into v1.7 branch and fix it here.

**Comment by JanTvrdik** [comment]
Why 2.0 and not 1.8? Do you plan to introduce BC breaks other than #259? Because changing required PHP version does NOT break BC for people who use Composer properly. Composer will still install 1.7 for them regardless of whether you call the version 1.8 or 2.0.

**Comment by Mikulas** [comment]
It is a breaking change and as such it must (as per semantic versioning) increment major version. Users of tester might not use composer.

**Comment by milo** [comment]
There will be BC breaks (https://github.com/nette/tester/milestones/2.0)

**Comment by JanTvrdik** [comment]
Close this?
