### ISSUE TITLE
Please provide test suite in archive

### ISSUE THREAD

**Issue by remicollet** [nette/tester#297]
Since acae20ae7ef6dc179d9db2c15c9ad093570d9470 tests are no more provided.

This is terrible.
We need test suite, when downloading this archive to be able to check the library.

**Comment by dg** [comment]
cc @JanTvrdik

**Comment by fprochazka** [comment]
Imho the tests don't belong to the distribution package. If you wanna run the tests, get the archive from the `git clone & checkout`

**Comment by remicollet** [comment]
I know we have s strong disagreement on this.
This have already discussed... in various place.

.gitattributes is IMHO a workaround for a bad composer usage.

All language library includes their test suite (perl, pear, nodejs, python...)

**Comment by dg** [comment]
I agree that .gitattributes is often used as a workaround for Composer and I am against it (https://github.com/nette/tracy/pull/90, examples should be part of ZIP although they are useless for Composer).

But `/tests` has IMHO sense only for developers and developers use Git.

**Comment by JanTvrdik** [comment]
@remicollet You can use `composer install --prefer-source`.

**Comment by remicollet** [comment]
I don't use composer.

I maintain package in downstream distribution which use the official archive, and run the test suite to ensure no regression.

**Comment by JanTvrdik** [comment]
The solution is the same – if you want to run tests, download the source and not the distribution package. I don't see a point in discussing this here any further as it has been discussed in many places before.

**Comment by dg** [comment]
All tests pass on every Tester commit.

**Comment by remicollet** [comment]
> All tests pass on every Tester commit.

Only in the distribution run by travis.
Not on real user distribution.
More Fedora CI doesn't monitor a single component, but the full PHP stack.

Any change in any dependency will raise a new build. Which include new PHP version, including Release Candidate, and this have already allowed to detect various BC (and block the release)

(e.g. 5.5.18RC1 introduce 2 regressions which break symfony and horde)

**Comment by milo** [comment]
Don't know the workflow... would be possible to clone the repo for CI?
```
git clone --branch v1.7.1 https://github.com/nette/tester.git tester-v1.7.1
```
