### ISSUE TITLE
Provide thread number when running paralel

### ISSUE THREAD

**Issue by milo** [nette/tester#301]
When run in paralel, there can be handy to have a current thread number. For example, prepare the same 8 databases, one for every thread.

Idea by @matej21

**Comment by JanTvrdik** [comment]
Nette tester does not use threads. Do you mean PID?

**Comment by hrach** [comment]
Probably not process id, but process number.

**Comment by JanTvrdik** [comment]
I think I got it now but both thread number and process number are confusing terms.

**Comment by milo** [comment]
In the doc is `-j 8` ... `Nette Tester uses 8 threads...`. I think the more precise terminology is queue.

**Comment by fprochazka** [comment]
That is a great idea! I was always hacking it somehow and it was very fragile.
