### ISSUE TITLE
TestCase: Ability to detect if tearDown was called within error processing or not

### ISSUE THREAD

**Issue by janedbal** [nette/tester#305]
With following test I get error from failed [mockery](https://github.com/padraic/mockery) expectation (```Method method() from Mockery_0_Tested should be called exactly 1 times but called 0 times```) and real problem (```E_RECOVERABLE_ERROR: Argument 1 passed to Mockery_0_Tested::method() must be of the type array, string given```) remains hidden. This might be very confusing when searching the bug.

```php
class Tested {
    public function method(array $arg) {}    
}

class Test extends Tester\TestCase {

    public function testError() {
        $tested = Mockery::mock(Tested::class);
        $tested->shouldReceive('method')->once();

        $tested->method('string');
    }

    protected function tearDown() {
        Mockery::close();
    }
}

(new Test)->run();
```

Possible solution might be passing some argument to tearDown method telling me if it is called during some error processing or not (then I would not call ```Mockery::close```). Or is there any working solution even now?

**Comment by milo** [comment]
I guess, [there](https://github.com/nette/tester/blob/5c4f5ec69d6894cd92bbeb1a216a63914f798761/src/Framework/TestCase.php#L128) should be muted exception too. And I see, I forgot refactore it for PHP 5.4 :flushed:

**Comment by janedbal** [comment]
@milo Any estimates when this will be fixed?

**Comment by milo** [comment]
In 2.0. I hope in May.

**Comment by janedbal** [comment]
Thanks!
