### ISSUE TITLE
Assertions aggregation into a named block

### ISSUE THREAD

**Issue by milo** [nette/tester#312]
### Idea

In Nette components test suits is quite common to use a `test()` function:

``` php
test(function () {
    Assert::...()
    Assert::...()
    Assert::...()
});
```

Sometimes, I'm using it too and I would like to make it official & supported. **Plus** add possibility to name such blocks of assertions. For example:

``` php
Assert::block('Invariability', function () {
    Assert::...()
    Assert::...()
    Assert::...()
});
```

The description of block will be shown in stack trace, e.g.:

```
-- FAILED: tests\RunnerOutput\JUnitPrinter.phpt
   Invariability
      Exited with error code 255 (expected 0)
      E_NOTICE: Undefined property: .....

      in src\Framework\Dumper.php(265)
      in src\Framework\Environment.php(127) Tester\Dumper::dumpException()
```

It should be nested, it can be used for [testMethods()](https://github.com/nette/tester/blob/93c1724ae63a9683d5f6b705d80586f0429bd163/src/Framework/TestCase.php#L163), it could solve the #293, related to #133.

Actually, it emulates `TestCase` methods stack trace a little bit.
### Implementation

``` php
public static function block($name, \Closure $cb)
{
    try {
        $cb();
    } catch (\Exception $e) {
        throw new AssertBlockException($name, $e);
    }
}
```

**Comment by dg** [comment]
I plan to replace `test(function() { … })` with `(function () { … })()` in PHP 7, so for me it is not useful, but it seems good to me.
