### ISSUE TITLE
Feature request: set environment for a test job

### ISSUE THREAD

**Issue by Fuco1** [nette/tester#318]
We use nette tester for integration testing, the combination of `@testCase` and test discovery makes it very simple to use & run parallel jobs.  However, one feature we miss is setting of environment variables for each job.  Databases and other services are configured through the environment, so it would be awesome if I could somehow set the variables for each job.

This has to be done via some meta-setting, outside of the **test code** because there it is already too late.  Something like `@dataProvider` or similar mechanism would be required.

What do you think?

**Comment by milo** [comment]
There will be [`NETTE_TESTER_THREAD`](https://github.com/nette/tester/commit/7dff568f4407658b2bed97b2daff5a447c8d4ac5) (Ref #301) env var in Tester 2.0. Is that what you mean?

**Comment by JanTvrdik** [comment]
@Fuco1 Why can't you just set them up in `setUp` method?

**Comment by Fuco1** [comment]
@milo We configure our application by setting environment variables like DATABASE_NAME, DATABASE_PASS and so on (according to http://12factor.net/config), so I would need to set those before running the tests.

@JanTvrdik I think it will be too late there because the settings are assigned to parameters in the configurator (for nette/di) and that is loaded with the bootstrap before the test, so it's already too late in the setUp (we have our own "environment" nette extension which sets up parameters by collecting the environment variables).

These will be integration tests so ideally they would run the same way as production, which also means loading the bootstrap.  I don't know if nette/tester is a good tool to do this, maybe it's not designed for such setup?

**Comment by JanTvrdik** [comment]
@Fuco1 Why can't you set them up in bootstrap then?

**Comment by Fuco1** [comment]
Because I don't know the values.  I hoped I would be able to tell nette/tester in a similar way as with dataprovider to set the environmnt of the subprocess (where the job runs).

Well... theoreticaly I could generate random database names in bootstrap.php

**Comment by JanTvrdik** [comment]
In that case I don't understand your problem at all. Hopefully someone else will be able to help you.

**Comment by fprochazka** [comment]
It looks like the job [is in fact passing the environment variables to jobs](https://github.com/nette/tester/blob/7dff568f4407658b2bed97b2daff5a447c8d4ac5/src/Runner/Job.php#L121). Anyways, generating random dbname is better - more isolation :)

**Comment by milo** [comment]
@Fuco1 I don't understand the issue too. Tester keeps environment variables (it is not in doc), so you can read it in every test by `getenv()`. Beside this, you can set them up in `--setup script.php`.

If you need a separated database for every job, some env var counter would be handy. But if you need a separated database for every parallel thread, the `NETTE_TESTER_THREAD` number is sufficient. For example with `-j 16`, the `NETTE_TESTER_THREAD` will be `1` to `16` depending on thread. When one test finished, the thread number will be reused for another one, but never in the same time.

**Comment by Fuco1** [comment]
@milo Right, that's exactly it.  I need a way to generate a database/service name for each job independently so that I can run stuff in parallel.  So I can use the thread counter as a seed for that, given those are unique at every given time to all the running jobs.

That's enough for my use-case, sorry for a somewhat chaotic description :P
