### ISSUE TITLE
Dataprovider is called before test's setUp method

### ISSUE THREAD

**Issue by CZechBoY** [nette/tester#323]
Is it bug or feature?
Where should I setup test case and prepare data for that test case?

My testcase: Test if user can load page without exception, dataprovider should provide only pages on which that user has allowed privilege.

**Comment by milo** [comment]
It is not an intended behaviour. Personally, I was never thinking about this kind of state-depending dataprovider.

TestCase could be refactored and dataprovider would return iterator.

**Comment by CZechBoY** [comment]
OK, I refactored dataProviders to setup their dependencies on their own.
