### ISSUE TITLE
Environment variable TERM

### ISSUE THREAD

**Issue by Beutlin** [nette/tester#324]
In Fedora I had to change the used environment variable from **term** to **TERM**. Otherwise colors are not used in my tests.
Would it be possible to update the file _src/Framework/Environment.php_?
Thanks a lot.

**Comment by JanTvrdik** [comment]
That's odd, `getenv('TERM')` should be the same as `getenv('term')`

**Comment by milo** [comment]
AFAIK, env var names are case sensitive on *NIX.

Colors detection can be updated.

**Comment by milo** [comment]
@Beutlin Are you sure that you didn't modify the letter case by your client? I don't use the Fodora OS but I didn't find, that `term` is somehow standard.

**Comment by milo** [comment]
Ehm, I misunderstood the issue (readed on phone). Please, send PR if you can.
