### ISSUE TITLE
ETA for 2.0.0 ?

### ISSUE THREAD

**Issue by remicollet** [nette/tester#325]
As all component are released for 2.4.0, this component is required to build all the others.

Have you any ETA for a release ?

**Comment by dg** [comment]
We have no eta, we are free developers with no boses :-)

**Comment by remicollet** [comment]
> We have no eta, we are free developers with no boses :-)

Of course ;)
But is just about an idea, days or months ?

**Comment by milo** [comment]
If @dg has no other plans, lets' say end of July? :o)

**Comment by milo** [comment]
I updated the [2.0 milestone](https://github.com/nette/tester/milestones/2.0) tags assignment.

**Comment by dg** [comment]
@milo It seems good, like a plan!

**Comment by milo** [comment]
Well, plans plans :(

**Comment by JanTvrdik** [comment]
I was a nice plan!

**Comment by dg** [comment]
https://twitter.com/MiloNemilo/status/798432365681016832 :-)

**Comment by milo** [comment]
@dg May I ask you to review issues from [2.0 milestone](https://github.com/nette/tester/milestones/2.0)? I cleaned it a little bit. I would like to release Tester 2.0 during January.

**Comment by f3l1x** [comment]
I looking forward to next release. How can I help you? :-)

**Comment by remicollet** [comment]
Happy birthday, issue :)

**Comment by milo** [comment]
Released ee0ad514d66409037a0e72fe798112fd8cdae92e

**Comment by remicollet** [comment]
Thanks
