### ISSUE TITLE
Enhance Tester\Assert class to check length of string

### ISSUE THREAD

**Issue by lukasneubauer** [nette/tester#327]
Is it possible to enhance Tester\Assert API to check length of string (similar to Assert::count())? Maybe by updating the Assert::count() method or by adding new method? Currently when you want to assert length of string it requires Assert::true(strlen($var) === $expectedLength).

**Comment by milo** [comment]
Hard question. What about UTF8 vs. non-UTF8 charsets? I would stay with:
```php
Assert::same(10, strlen($str));
Assert::same(10, mb_strlen($str));
```

**Comment by jkuchar** [comment]
Till this will be resolved in PHP, I like what @milo proposed.

Length depends on encoding of test file and Tester currently does not specify how you should encode your test files.
