### ISSUE TITLE
Feature request: Assert::equal should not ignore key order

### ISSUE THREAD

**Issue by Fuco1** [nette/tester#332]
I know this is problematic, and I see it is documented, but damn, it caught me off guard.

I always assumed that `same` vs `equal` is simply `===` vs `==`.  But `[1,2] == [2,1]` is false,  What is natural to expect is to let `[1,2] == ['1',2]` be true, but not switching up order.

In some cases, it might be convenient to ignore key order, but that seems like a fine candidate for `equalIgnoreOrder` or something like that.  Many a time key order is important, given that array is PHP's data structure for everything.

This change breaks BC, which might be an argument against :/

**Comment by dg** [comment]
You are right for *lists*, where order is important, but for *maps* is natural to expect that `['name' => 'abc', 'id' => 12]` is equal to `['id' => 12, 'name' => 'abc']`.

**Comment by Fuco1** [comment]
Correct.  So maybe we could have a variant `equalList` or some such.  That would keep backward compatibility and give us a version that also checks key order.

Other problem is what to do with nested structure... I can have a list of maps or maps of lists.  Hm, seems a bit nastier than at first sight.

**Comment by dg** [comment]
What about check order when array is list?

**Comment by Fuco1** [comment]
The case where I stumbled on this problem is a map with numeric keys with gaps (it represents days in the future where I can order and the value is delivery day, so `[1 => 4, 3 => 7, 10 => 15]` and so on.

The bug was that when the user added new pair, it got added to the end, and so keys weren't ordered anymore.  However, the tests still passed and so nobody found out until now :)

So, is that a list if it has gaps?  I'm not sure about the naming conventions.

**Comment by dg** [comment]
Btw why are you using `equal` instead of `same`?

**Comment by Fuco1** [comment]
This is a legacy application which doesn't care much about what data types it pulls from the database, so there are routinely numerical values as stirngs and so on.  I've fixed that now (for this particular case) and changed the tests to `same`, but in general... you never know what crazy code depends on things being of various types.

**Comment by dg** [comment]
But `equal` checks for datatypes strictly, it only ignores key order and object identity. I.e. `Assert::equal([1,2], ['1',2])` is FALSE.

I must clarify that `Assert::equal([1,2], [2,1])` is FALSE too.
