### ISSUE TITLE
Timezone not specified error in jUnit output

### ISSUE THREAD

**Issue by fmasa** [nette/tester#333]
Probably related to https://github.com/nette/tester/issues/195

When I use junit output I get following error:

```
$ vendor/bin/tester tests/unit -o=junit
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>

Error: date(): It is not safe to rely on the system's timezone settings. You are
 *required* to use the date.timezone setting or the date_default_timezone_set()
function. In case you used any of those methods and you are still getting this w
arning, you most likely misspelled the timezone identifier. We selected the time
zone 'UTC' for now, but please set date.timezone to select your timezone.
```

I have default timezone specified in bootstrap.php.
This doesn't work either:

```
$vendor/bin/tester tests -d date.timezone=Europe/Prague -o=junit
```

---

This is PHP version that is affected in my container:

```
$ php -v
PHP 5.6.22 (cli) (built: May 27 2016 23:37:10)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

This one is not:

```
PHP 5.6.20-0+deb8u1 (cli) (built: Apr 27 2016 11:26:05)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
```

It's caused by date() call in [JunitPrinter:68](https://github.com/nette/tester/blob/7d29c02f3216a1c4debe4c6475830b5884786922/src/Runner/Output/JUnitPrinter.php#L68), but I don't understand why does it work for one version and not for the other.

**Comment by fmasa** [comment]
Should I prepare PR with fix? @milo

**Comment by milo** [comment]
The `vendor/bin/tester` only runs the test runner `php src/tester.php ...` and `JunitPrinter` is called in this process, not in the inner PHP processes. So `bootstrap.php` has no effect.

Try `php -d 'date.timezone=Europe/Prague' src/tester.php tests`. IMHO, time zone is missing in php.ini for `PHP 5.6.22`.

Not sure if test runner should set timezone for itself or just mute it in JunitPrinter.

**Comment by fmasa** [comment]
IMHO it should just mute it to be consistent with https://github.com/nette/tester/issues/195 resolution. I see no problem with default system timezone for that.
