### ISSUE TITLE
Assert::exception doesn't match message properly because of escaping sequence

### ISSUE THREAD

**Issue by mrtnzlml** [nette/tester#338]
Failing test:

```php
Assert::exception(function() {
	throw new \Exception('Exception message with %%escaping sequence%%.');
}, 'Exception', 'Exception message with %%escaping sequence%%.');
```

Result (it should pass):

![screenshot from 2016-10-01 20 54 56](https://cloud.githubusercontent.com/assets/978368/19016422/55422636-8819-11e6-9c78-f5982ffa4bf4.png)

Unfortunately I am not able to send PR with fix.
Another failing test: https://travis-ci.org/adeira/compiler-extension/jobs/164310809

**Comment by JanTvrdik** [comment]
This is expected behavior, use %% instead of each %

**Comment by mrtnzlml** [comment]
I understand that solution is this:

```php
Assert::exception(function() {
    throw new \Exception('Exception message with %%escaping sequence%%.');
}, 'Exception', 'Exception message with %%%%escaping sequence%%%%.');
```

But 1) it's weird and more importantly 2) it says that expected message is `Exception message with %%escaping sequence%%.` but got `Exception message with %%escaping sequence%%.` and that's exactly the same text. This is super weird... :-/

I don't think this report is invalid.

**Comment by JanTvrdik** [comment]
> I don't think this report is invalid.

And what would you expect Tester to do?

**Comment by mrtnzlml** [comment]
Oh, you are right - from this point of view this make sense.

It wasn't clear what is going on. Fortunatelly I am watching every PR in Nette so I knew about it, but still it's so confusing... :)

But now it's invalid even for me. Thanks for explanation and sorry for bad bad issue.
