### ISSUE TITLE
Support running failed tests first

### ISSUE THREAD

**Issue by JanTvrdik** [nette/tester#341]
See https://github.com/lstrojny/phpunit-clever-and-smart#mission for inspiration

**Comment by hrach** [comment]
Would be very powerfull with `--stop-on-fail` & `--watch`

**Comment by milo** [comment]
Some idea to not require persistent storage (temp dir)?

**Comment by JanTvrdik** [comment]
I don't think it is possible to remember anything without storage.

**Comment by mrtnzlml** [comment]
For development it's also very usefull to run only tests related to changed files. This is how Jest works. You can run all tests (like in Nette/Tester) or run Jest with option -o and it will automatically find tests related to changed files to execute in your project. It's lovely feature... :)

It's different approach how to achieve similar behavior: run just subset of tests related to the application files you are working on.
