### ISSUE TITLE
Composer run-scripts ommit tester colors

### ISSUE THREAD

**Issue by f3l1x** [nette/tester#343]
I do not know if it's bug or it's a feature. :question: 

`composer run-script nette-tester` strips colors in output. On the other hand `composer run-script codesniffer` does not. 

Name of the scripts are fake, just for demonstration.

------

CodeSniffer: https://travis-ci.org/contributte/logging/jobs/181436162#L222

![selection_001](https://cloud.githubusercontent.com/assets/538058/21119031/e34aeb54-c0c0-11e6-9c18-86328206d897.png)

NetteTester: https://travis-ci.org/contributte/logging/jobs/181436162#L244

**Sections shoud be green**.

![selection_002](https://cloud.githubusercontent.com/assets/538058/21119025/dcd63b52-c0c0-11e6-8732-81712b5ed1bf.png)

**Comment by JanTvrdik** [comment]
detecting support for colors always was and likely always will be magic

**Comment by milo** [comment]
Tester [detects](https://github.com/nette/tester/blob/7700c4de0ea523e6a687661705fccc3741d8636b/src/Framework/Environment.php#L73) if STDOUT is terminal. If not, colors are disabled.

First guess... phpcs ignores it.
Second guess... composer uses probably symfony EventDispatcher and it somehow redirects stdout, so stdout is not a terminal.

Maybe I'm wrong, I don't know mentioned tools source.

You can add `--colors` for tester to force colors usage.

**Comment by f3l1x** [comment]
Command `tester --colors` works like a charm! Thank you.
