### ISSUE TITLE
DomQuery does not support SVG

### ISSUE THREAD

**Issue by JanTvrdik** [nette/tester#354]
Another DOMDocument-caused bug. DomQuery does not support SVG.
Current workaround I use is `Strings::replace($html, '#<svg[^>]*+>.+?</svg>#s', '');`

Our SVG code

~~~html
<svg role="img" aria-label="" title="" class="shape shape-share-fb view-head button-icon">
	<use xlink:href="#shape-share-fb"></use>
</svg>
~~~

**Comment by genesiscz** [comment]
Is this getting a fix?
