### ISSUE TITLE
Add something like @removeFromCoverage to remove class / method from code coverage

### ISSUE THREAD

**Issue by lukasneubauer** [nette/tester#359]
- bug report? no
- feature request? yes
- version: 2.x

It would be great to have something like `@removeFromCoverage` which could be placed on class or method annotation docblock to remove this code from code coverage.

For example, if you have this code

```
<?php

/**
 * @removeFromCoverage
 */
class Foo
{
    public function bar() {}
}
```

The whole class `Foo` would be removed from coverage.

And if you have this code

```
<?php

class Foo
{
    /**
     * @removeFromCoverage
     */
    public function bar() {}
}
```

The method `bar` would be removed from code coverage.

This could be useful for such a code, like simple setters or getters, which do not need to be tested

```
<?php

class Foo
{
    private $bar;

    /**
     * @removeFromCoverage
     */
    public setBar($bar)
    {
        $this->bar = $bar;
    }

    /**
     * @removeFromCoverage
     */
    public function getBar()
    {
        return $this->bar;
    }

    public function someOtherMethodNotRemovedFromCoverage()
    {
        // ...
    }
}
```

Or for exception classes, that have no methods

```
<?php

/**
 * @removeFromCoverage
 */
class SomeException extends Exception
{
}
```

**Comment by dg** [comment]
I closing it for lack of interest.
