### ISSUE TITLE
Show count assertions

### ISSUE THREAD

**Issue by grogy** [nette/tester#360]
- bug report? no
- feature request? yes
- bc-break? no

### Description
Nette\Tester does not show count of assertions in results. For example another testing tools display `OK (12 tests, 33 assertions)`, Nette\Tester show only `OK (2 tests, 2.1 seconds)`. What is the reason for does not display it? What about display something like `OK (2 tests, 5 assertions, 2.1 seconds)`?

### Why I want add it
"Sometimes" I have to refactoring old smell code. If the class has high cyclomatic complexity then I have too many assertion in test (I mean it is bad, but I want test it now and refactor to smaller classes when I will have tests).

If the idea will be correct then I can send PR.

**Comment by milo** [comment]
Idea is OK, would be useful for check during tests refactoring. Implementation is problematic. Have to pass from test runtime process to parent Runner's process.

**Comment by midlan** [comment]
I miss this feature too. I was used to workflow:

1. add (e.g. 2) new asserts
2. run tests
3. check if the total count of asserts raised (by two)

**Comment by grogy** [comment]
Thanks for feedback. I was start with research now. It seems non-trivial as says @milo :-)

**Comment by dg** [comment]
I'm closing, but feel free to send PR.
