### ISSUE TITLE
Remove the need for $testcase->run()

### ISSUE THREAD

**Issue by Fuco1** [nette/tester#361]
- bug report? no
- feature request? yes
- version: 1.7.1

### Description

Because tests are also code it would be very valuable to be able to run static analysis on them.  We use [PHPStan](https://github.com/phpstan/phpstan) in all our projects now and it is really painful when you suddenly go to writing tests and the support is not there (especially if your editor/IDE supports it).

However, there are two issues with nette tester which stop us from using this tool:

1. Files have to be named `.phpt` which breaks autoloading (I have not found a way to convince composer to generate autoloads for `.phpt` files).
2. PHPStan actually loads the files and so it would run the test suite while doing the analysis => this is really really bad obviously.

Wouldn't it be possible to use something like robotloader to crawl the test directory and extract all the classes implementing `TestCase`.  Then the runner would go over these files, load them, make instances and run the tests.

One problem I can see is that often you want to pass some services from DI to the test (for example for integration tests) and so you need to have a way to do this.  Maybe registering tests in DI? (usually you have a separate bootstrap anyway so you can just add an extra config file there for tests).  Alternatively inject the container itself (which is far simpler to set up) and let the test author pick the services... not ideal but acceptable for tests I guess.

I think that even ignoring PHPStan and its quirks (it is not really a static analysis /shrug) it would be valuable to have the classes defined in files without the `run` call.  PHPUnit seems to do it that way as well so it should be feasible.

**Comment by milo** [comment]
add 1) In 2.x, test runner will search for `*.phpt` and `*Test.php`.

add 2) Idea of Tester is possibility to run test as an ordinary script by `php test.phpt`. That's why the `TestCase::run()` is called. If you don't need it, you can run it conditionally by:
```php
if (getenv(Tester\Environment::RUNNER)) {
    $testCase->run();
}
```

**Comment by Fuco1** [comment]
Thanks for the quick reply.  The second idea works great, I will transform all our tests to use this check.  With that and a file manually added to the autoloader I can run the analysis.

I don't like the `*Test.php` convention so I will have to figure out how to dump the autoload data.

I think with the above workaround this issue can be closed.

**Comment by JanTvrdik** [comment]
> Wouldn't it be possible to use something like robotloader

PhpStan supports autoloading of `*.phpt` files. See https://github.com/phpstan/phpstan/blob/5534a1d949f7f5baadabf73316c410a3b449f306/src/Command/AnalyseCommand.php#L182-L193

**Comment by Fuco1** [comment]
@JanTvrdik Wow that's handy!  I should go over the readme again, so many new features /o\

**Comment by CZechBoY** [comment]
Also you can extend some BaseTestCase class and override run method with the same condition. It is more robust.
