### ISSUE TITLE
Minimal PHP version 5.6 (or 7.0)

### ISSUE THREAD

**Issue by dg** [nette/tester#364]
I know the Tester works reliably with PHP 5.4 and there is no need to bump minimal required version. On the other hand, I think that end support for PHP < 5.6 will not hurt anyone because the older Tester release is fully usable.

Theoretically, it's possible to bump to PHP 7. Nette for PHP 5.6 is still a supported branch, but it receives only bugfixes, so it will not require new Tester features.

**Comment by milo** [comment]
If you are OK with 7.0, I would go for it. In Debian Stretch (released 17.6.2017) is PHP 7.0. I have some 5.6 librarires too, slowly leaving them, but as you wrote, Tester 1.8 is OK for them. At "worst", new 1.x branch can be opened.

**Comment by milo** [comment]
Vote on https://twitter.com/MiloNemilo/status/885019685829435394

**Comment by milo** [comment]
There is a 20-25% votes for 5.6. It is not so low number, so I would stay with 5.6

**Comment by dg** [comment]
OK

**Comment by f3l1x** [comment]
@milo Oh, that's a pity.

**Comment by dg** [comment]
I think that supporting version 5.6 is fine. Preparing a version with PHP 7 features would delay the release.
