### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by milo** [nette/tester#373]
I'm ready to release 2.0.0. From my point of view, the rest of actual issues can be solved without BC break in 2.x.

Now I'm working on doc and blog post.

**Comment by milo** [comment]
Released ee0ad514d66409037a0e72fe798112fd8cdae92e

**Comment by dg** [comment]
![image](https://media0.giphy.com/media/1PMVNNKVIL8Ig/giphy.gif)
