### ISSUE TITLE
Remove the date and time from the coverage report

### ISSUE THREAD

**Issue by rostenkowski** [nette/tester#376]
- bug report? **no**
- feature request? **yes**

### Description

What do you thing about remove the date and time from the coverage report? 

IMHO it is useless information, because the report is either in sync with the code or not, regardless some date and time caption.

When nothing has changed in the code the report should stay untouched from the git point of view, but the date and time of the report generation changes everytime.

```html
<footer>
    <p>Generated by <a href="https://tester.nette.org">Nette Tester</a> at 2017/09/19 16:01:43</p>
</footer>
```

**Comment by milo** [comment]
I do not commit code coverage, so I never run into this issue. But I occasionally share the report and in this case, generating time is important. I would leavit as it is.

What about some git hook script which will remove the timestamp from report?

**Comment by rostenkowski** [comment]
What about `--coverage-timestamp`?

**Comment by rostenkowski** [comment]
Don't get it wrong, it's not a trivial job to remove that timestamp. It would require some HTML parser to be error prone. Some ugly **sed** command should do the job too.

```bash
sed -i "s/at [0-9]\{4\}\/[0-9]\{2\}\/[0-9]\{2\} [0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}//g" COVERAGE.html
```
But you can only hope your source code does not contain something similar. Limit that sed command only to `<footer>` is beyond my skills.

It would be much more comfortable to be able to choose not to insert that timestamp at all instead of removing it from the large HTML file.

**Comment by rostenkowski** [comment]
Next option could be `--coverage-template <FILE>`.

**Comment by rostenkowski** [comment]
If you are not interested I am closing it for now. Thank you for your time :-)

**Comment by milo** [comment]
I'm interested in every issue, but when you close it, it means you are not interested.
