### ISSUE TITLE
Show dataProvider section name

### ISSUE THREAD

**Issue by nechutny** [nette/tester#377]
- bug report? no
- feature request? yes

### Description

When using @dataProvider annotation with ini file it will be nice to show data's section name when test fails, becase sometimes have sections a lot of variables and difference is at stripped end, so searching which one failed is almost impossible.

**Comment by milo** [comment]
How looks fail now? There should be printed [test signature](https://github.com/nette/tester/blob/8cf24cf8c07defa85de7e2543c92db7bd3ded5a0/src/Runner/Test.php#L76), arguments including.

**Comment by nechutny** [comment]
Fail output looks:

> -- FAILED: Agreement Corporate ACL | CorporateAgreementACL.phpt
>    Failed: User manage document: FALSE should be TRUE in testManageDocument('userId' => '666', 'corporateId' => '42', 'onlyOwnDocument' => '1', 'canSeeConfidential' => '1', ...)

Ini file with data looks like

> [notOwner]
> ; Test document owned by someone else
> userId=666
> corporateId=42
> onlyOwnDocument=1
> canSeeConfidential=1
> isCorporateAdmin=0
> allDocuments='NONE'
> agreementOwner=93
> agreementConfidential=0
> userShareLevel='NONE'
> departmentShareLevel='NONE'
> expected=FALSE

I really can't determine which test fail, when difference is eg. departmentShareLevel, but show section name will be really helpfull.

**Comment by milo** [comment]
Sure, it must be printed and I thought, it is. I'll check it.

**Comment by nechutny** [comment]
Thanks
