### ISSUE TITLE
Missing response code assertion

### ISSUE THREAD

**Issue by Benko11** [nette/tester#391]
Your tester currently does not provide a way to assert the HTTP code assertion, or not a way that I'm aware of. Either way, it could prove really useful to implement it like Assert::status(200)

**Comment by dg** [comment]
You can assert it via annotation @httpCode https://tester.nette.org/en/#toc-httpcode

**Comment by milo** [comment]
As @dg wrote, the `@httpCode` handles this case. I can't imagine how would `Assert::status()` work. If you have use case for it, please reopen.
