### ISSUE TITLE
E_USER_WARNING: File's modification time is in the future. Cannot update it: touch(): Tester\FileMock::stream_metadata is not implemented!

### ISSUE THREAD

**Issue by aleswita** [nette/tester#406]
Version: 2.1.0

### Bug Description
After this [commit](https://github.com/nette/latte/commit/86c44cd33606c3a0eb3216be5e3eecdad6679e9b#diff-9b136984d993d1b0c7ef54354be950e5) in Latte (v2.5.2) my [test](https://github.com/contributte/translation/blob/master/tests/Tests/Translator.phpt#L160) failed on 
**E_USER_WARNING: File's modification time is in the future. Cannot update it: touch(): Tester\FileMock::stream_metadata is not implemented!**, look on [Travis](https://travis-ci.org/contributte/translation/jobs/564696503)

### Possible Solution
Relese new Tester version with this [commit](https://github.com/nette/tester/commit/c04d00b579bdcfac50f44365040397acf6f41f77)

**Comment by aleswita** [comment]
@milo it's possible release minnor version (2.1.1, 2.2.1)?

**Comment by milo** [comment]
I'll release new version during the weekend.

**Comment by milo** [comment]
The 2.3.0 is out. https://github.com/nette/tester/releases/tag/v2.3.0

**Comment by aleswita** [comment]
Tnx!
