### ISSUE TITLE
Support for minor distinction of exceptions

### ISSUE THREAD

**Issue by janbarasek** [nette/tester#408]
Hello, I have suggestion for new cool feature about exceptions. If it make sense I can send pull request.

Imagine you want test some method throw correct exception. Now you must validate by message, but it can be wrong, because you can use more minor distinction of exceptions.

For example create typed exception (`DatabaseException.php`):

```php
class DatabaseException extends \Exception
{

	public static function connectionRefused(): void
	{
		throw new self('Connection to server was refused.');
	}

}
```

In source code is simply use:

```php
class MySqlDriver extends DatabaseDriver
{

	public function connect(): Connection
	{
		if (...) {
			return new Connection(...);
		} else {
			DatabaseException::connectionRefused();
		}
	}

}
```

As you can see, source code is more clear. In case when you want use some parameters, you can.

In test `Assert` syntax can be like:

Old:

```php
Assert::exception(function (): void {
    throw new DatabaseException('Message');
}, DatabaseException::class, 'Message');
```

New (suggestion):

```php
Assert::exception(function (): void {
    throw new DatabaseException::connectionRefused();
}, DatabaseException::class, 'connectionRefused()'); // Or another syntax
```

Thanks.

**Comment by JanTvrdik** [comment]
Do I understand properly that you want to check the exception trace?

**Comment by janbarasek** [comment]
@JanTvrdik Yes, very similar to `debug_backtrace()`.

**Comment by dg** [comment]
It is too specific issue. Please create your own assert for it.
