### ISSUE TITLE
`\Tester\TestCase::tearDown` is not executed on php crash

### ISSUE THREAD

**Issue by midlan** [nette/tester#430]
Version: 2.4.0

### Bug Description
If there is some issue crashing the PHP process, the method `\Tester\TestCase::tearDown` is not executed.

### Steps To Reproduce
```php
<?php

use Tester\Assert;

(new class extends Tester\TestCase {

    public function testFoo()
    {
        $this->testFoo(); //infinite recursion
    }

    protected function tearDown() {

        parent::tearDown();

        echo 'tearDown';
    }

})->run();
```

Note the ifinite recursion. It will crash the php and such result is reported by tester:
```
-- FAILED: FooTest.php
   Exited with error code 137 (expected 0)
```

### Expected Behavior
I would like the `tearDown` to be executed. But it's not.

### Possible Solution
I personally don't know the solution.

**Comment by dg** [comment]
Infinite recursion is a logical error in the test and must be fixed by the programmer. There's nothing the Tester can do about it.

**Comment by midlan** [comment]
@dg I agree programmer should fix it. I only demonstrated the problem on recursion. There is bunch of other situations which cause php to crash. The point is that the teardown method is not executed.

I did some research on it and it seemed imposible to handle such errors with PHP to me, so I created the issue. Maybe there is someone who knows some special technique :)

**Comment by dg** [comment]
When it crashes, there is no guarantee that tearDown() will be called.
