### ISSUE TITLE
Display name of concrete test method in console-lines output

### ISSUE THREAD

**Issue by Marian-Kechlibar** [nette/tester#448]
Nette Tester currently supports a new output format console-lines, which looks very nice and, IMHO, is the most informative of them all. An optimal combination of colors and information, as far as my human eyes go.

What I nevertheless miss is the names of individual methods that are running. The "log" output format has them, but is completely grey and thus less informative for a human to look at. The "console-lines" format doesn't have them.

As a result, the output is less informative:

· 1/12 Admin\CertificateTest.php FAIL in 0.00 s
· 2/12 Admin\CertificateTest.php FAIL in 0.00 s
· 3/12 User\CertificateTest.php FAIL in 0.00 s
· 4/12 Admin\CertificateTest.php OK in 1.33 s
· 5/12 Admin\CertificateTest.php OK in 0.71 s
· 6/12 Admin\CertificateTest.php OK in 0.70 s
· 7/12 Admin\CertificateTest.php OK in 0.34 s
· 8/12 Admin\CertificateTest.php OK in 0.34 s
· 9/12 Admin\CertificateTest.php OK in 0.39 s

I propose a wider format like this

· 1/12 Admin\CertificateTest.php (testCertificateList) FAIL in 0.00 s

**Comment by smuuf** [comment]
This is something I've also been wanting to add, so I finally did it. Thanks for the nudge 🐣
