### ISSUE TITLE
Ability to produce a console and a file output at the same time

### ISSUE THREAD

**Issue by Marian-Kechlibar** [nette/tester#452]
So, Nette Tester as of 2.5.3 supports various output formats, some of which are more human-readable (e.g. console-lines) and some are more suitable for machine consumption (junit).

In my own use, I would love to do both. So, during the same run, produce a human-readable console output for me to observe, and at the same time, produce a machine-readable file stored on the disk for further automatic processing.

Therefore, I propose the following feature. The -o switch, which currently determines precisely one output format, _could_ also take a string like this:
`
-o console=lines,file=junit`

parse the string and print out the testing output to the console using the "console-lines" format and simultaneously to a file using the junit format. You could, of course, use just one, too, so:

`
-o console=lines`

or
`
-o file=junit`

or 

`
-o console=none,file=junit`

etc. etc.

To keep backward compatibility with earlier releases of Nette Tester, if there is no '=' character present in the argument of -o, it would behave exactly as before, so outputting one format only directly into stdout.

I am willing to try to tackle this and create a pull request, but I would first like to discuss the details first with all concerned developers, so that I don't do anything useless.

One important detail is where precisely to store the output file. I propose another parameter

`
-opath path_to_output_file`

which could set the output path explicitly. If -opath were not specified, either some default path could be used (./nette-tester-output ?), or it could be set up dynamically in the --start-script.

**Comment by milo** [comment]
Hi,
this is already possible, option `-o` can be used multipletimes. E.g.

```
tester -o console -o tap:file.txt -o log:file.log tests
```

It is mentioned in [documentation](https://tester.nette.org/en/running-tests#toc-o-console-console-lines-tap-junit-log-none).

>The -o option can be repeated multiple times to generate multiple formats at once.

**Comment by Marian-Kechlibar** [comment]
> Hi, this is already possible, option `-o` can be used multipletimes. E.g.
> 
> ```
> tester -o console -o tap:file.txt -o log:file.log tests
> ```
> 
> It is mentioned in [documentation](https://tester.nette.org/en/running-tests#toc-o-console-console-lines-tap-junit-log-none).
> 
> > The -o option can be repeated multiple times to generate multiple formats at once.

I can't believe I overlooked this. Thanks. I will close this request and start another one which involves paths to output.
