### ISSUE TITLE
Dynamic output file for format

### ISSUE THREAD

**Issue by Marian-Kechlibar** [nette/tester#453]
As mentioned by @milo in an already closed (meritless) issue, Nette Tester can produce output in multiple formats at the same time, like this:

`tester -o console -o tap:file.txt -o log:file.log tests`

I propose an enhancement of this capability. By specifying 

`tester -o console -o tap:file.txt -o log:dynamic tests --setup=XXX`

the output path for that particular format would only be determined by the setup script. 

The 'dynamic' keyword would only be allowed if --setup was used, and the setup script would be obligated to actually determine the output path.

This would solve a use case where you want to write to a directory created in the setup script itself. 

I am willing to try and implement this.

**Comment by milo** [comment]
I don't see any benefit of such feature. You can create dir for logs before running tester. As any CI offers.
Or setup output handlers in `--setup` script. Like `$runner->outputHandlers[] = ....`.

**Comment by Marian-Kechlibar** [comment]
> You can create dir for logs before running tester

It was my impression that the setup script was intended to give the user a lot of freedom in this regard, so that many parameters could be set up dynamically, and not be predetermined at the command line. Possibly, you don't know in advance in which environment the test is going to be running, and want to adapt dynamically to what you find out in the setup script.

OK, so how do I set up a dynamic path using output handlers? This is not an extensively documented feature.

**Comment by milo** [comment]
For example:
```php
# setup.php
<?php

$logDir = __DIR__ . '/log';
mkdir($logDir);
$runner->outputHandlers[] = new Tester\Runner\Output\JUnitPrinter("$logDir/junit.xml");
```

```
tester --setup setup.php tests
```

**Comment by Marian-Kechlibar** [comment]
Thank you very much!
